modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/TeamMoegMC/Steam-Powered/issues"
[[mods]] #mandatory
modId = "steampowered" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Create: Steam Powered" #mandatory
authors = "[TeamMoeg] YueSha, khjxiaogu, goumo_g"
credits = "The Create Team for the wonderful mod."
description = '''
Expanding Create mod to the Steam Age.

Developers: YueSha, khjxiaogu
Artists: goumo_g

Contributors (in no particular order):
MRH0, SpottyTheTurtle, jetpacker06, and all Contributors on GitHub.
'''
[[dependencies.steampowered]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.0.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.steampowered]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.steampowered]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.f,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.steampowered]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.10,0.6.11)"
    ordering="AFTER"
    side="CLIENT"
